let isEnabled = true;
let idCounter = 1;

const adRules = [
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*', resourceTypes: ['script'], requestDomains: ['doubleclick.net', 'googlesyndication.com', 'googleadservices.com', 'adnxs.com', 'adsrvr.org', 'adform.net', 'advertising.com', 'rubiconproject.com', 'pubmatic.com', 'openx.net', 'criteo.com', 'taboola.com', 'outbrain.com', 'mgid.com', 'revcontent.com', 'zergnet.com', 'teads.tv', 'amazon-adsystem.com', 'media.net', 'bidswitch.net', 'casalemedia.com', 'contextweb.com', 'lijit.com', 'moatads.com', 'quantserve.com', 'scorecardresearch.com', 'comscore.com', 'omniture.com', 'bluekai.com', 'krxd.net', 'adtech.de', 'adtechus.com', 'smartadserver.com', 'adroll.com', 'perfectaudience.com', 'lingeriescripts.com', 'adservice.google.com', 'ads.facebook.com', 'ads.linkedin.com', 'ads.twitter.com', 'ads.tiktok.com', 'ads.instagram.com', 'ads.yahoo.com', 'ads.bing.com', 'ads.reddit.com', 'ads.pinterest.com', 'ads.snapchat.com', 'advertising.amazon.com'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*', resourceTypes: ['image'], requestDomains: ['doubleclick.net', 'googlesyndication.com', 'googleadservices.com', 'adnxs.com', 'adsrvr.org', 'advertising.com', 'rubiconproject.com', 'pubmatic.com', 'openx.net', 'criteo.com', 'taboola.com', 'outbrain.com', 'mgid.com', 'bidswitch.net', 'casalemedia.com', 'amazon-adsystem.com', 'media.net', 'adform.net', 'adsymptotic.com', 'flashtalking.com'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*', resourceTypes: ['sub_frame'], requestDomains: ['doubleclick.net', 'googlesyndication.com', 'googleadservices.com', 'adnxs.com', 'advertising.com', 'criteo.com', 'taboola.com', 'outbrain.com', 'amazon-adsystem.com', 'smartadserver.com'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*', resourceTypes: ['xmlhttprequest'], requestDomains: ['google-analytics.com', 'googletagmanager.com', 'analytics.google.com', 'facebook.com/tr', 'connect.facebook.net', 'hotjar.com', 'mixpanel.com', 'segment.io', 'amplitude.com', 'heap.io', 'mouseflow.com', 'fullstory.com', 'crazyegg.com', 'optimizely.com', 'branch.io', 'appsflyer.com', 'adjust.com', 'kochava.com', 'singular.net', 'newrelic.com', 'sentry.io', 'bugsnag.com', 'logrocket.com', 'tiktok.com', 'tiktokv.com'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*doubleclick\\.net.*', resourceTypes: ['script', 'image', 'sub_frame', 'object', 'xmlhttprequest', 'beacon', 'websocket'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*googlesyndication\\.com.*', resourceTypes: ['script', 'image', 'sub_frame'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*googleadservices\\.com.*', resourceTypes: ['script', 'image', 'sub_frame', 'main_frame', 'xmlhttprequest', 'beacon'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*googleadservices\\.com\\/pagead\\/.*', resourceTypes: ['script', 'image', 'sub_frame', 'main_frame', 'xmlhttprequest'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*googleadservices\\.com\\/pagead\\/aclk.*', resourceTypes: ['main_frame', 'sub_frame', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*pagead\\/aclk.*', resourceTypes: ['main_frame', 'sub_frame', 'image', 'script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*\\/aclk\\?.*', resourceTypes: ['main_frame', 'sub_frame', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*\\?gclid=.*', resourceTypes: ['main_frame', 'sub_frame', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*\\?utm_.*', resourceTypes: ['main_frame', 'sub_frame', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*adurl.*', resourceTypes: ['main_frame', 'sub_frame', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*\\&rf=.*', resourceTypes: ['main_frame', 'sub_frame'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*\\?nb=.*', resourceTypes: ['main_frame', 'sub_frame'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*google-analytics\\.com.*', resourceTypes: ['script', 'beacon', 'xmlhttprequest'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*googletagmanager\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*googletag\\.com.*', resourceTypes: ['script', 'json'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*pagead2\\.googlesyndication\\.com.*', resourceTypes: ['script', 'image', 'sub_frame'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*tpc\\.googlesyndication\\.com.*', resourceTypes: ['script', 'image', 'sub_frame'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*ads\\.google\\.com.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*googleads\\.g\\.doubleclick\\.net.*', resourceTypes: ['script', 'image', 'sub_frame'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*static\\.doubleclick\\.net.*', resourceTypes: ['script', 'image', 'sub_frame'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*cm\\.doubleclick\\.net.*', resourceTypes: ['script', 'image', 'beacon'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*stats\\.g\\.doubleclick\\.net.*', resourceTypes: ['script', 'image', 'beacon'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*partner\\.doubleclick\\.net.*', resourceTypes: ['script', 'image', 'sub_frame'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*m\\.doubleclick\\.net.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*adclick\\.g\\.doubleclick\\.net.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*video\\.doubleclick\\.net.*', resourceTypes: ['script', 'image', 'sub_frame'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*display\\.doubleclick\\.net.*', resourceTypes: ['script', 'image', 'sub_frame'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*buy\\.doubleclick\\.net.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*gstatic\\.com\\/promoted.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*1e100\\.net.*', resourceTypes: ['script', 'image', 'beacon'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*2mdn\\.net.*', resourceTypes: ['script', 'image', 'sub_frame'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*googleadservices\\.com\\/pagead\\/.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*googlesyndication\\.com\\/pagead\\/.*', resourceTypes: ['script', 'image', 'sub_frame'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*admob\\.com.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*googlesyndication\\.com\\/safeframe\\/.*', resourceTypes: ['script', 'sub_frame'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*googleadservices\\.com\\/xgfp\\.js.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*apis\\.google\\.com\\/js\\/adsbygoogle.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*pagead\\/js\\/.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*ads\\/.*client=.*', resourceTypes: ['script', 'json'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*\\/ads\\/.*', resourceTypes: ['script', 'image', 'sub_frame'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*\\.googlesyndication.*\\.com.*', resourceTypes: ['script', 'image', 'sub_frame'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*adnxs\\.com.*', resourceTypes: ['script', 'image', 'sub_frame'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*appnexus\\.com.*', resourceTypes: ['script', 'image', 'sub_frame'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*criteo\\.com.*', resourceTypes: ['script', 'image', 'sub_frame'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*criteo\\.net.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*taboola\\.com.*', resourceTypes: ['script', 'image', 'sub_frame'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*outbrain\\.com.*', resourceTypes: ['script', 'image', 'sub_frame'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*mgid\\.com.*', resourceTypes: ['script', 'image', 'sub_frame'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*rubiconproject\\.com.*', resourceTypes: ['script', 'image', 'sub_frame'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*pubmatic\\.com.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*openx\\.net.*', resourceTypes: ['script', 'image', 'sub_frame'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*amazon-adsystem\\.com.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*media\\.net.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*bidswitch\\.net.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*casalemedia\\.com.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*smartadserver\\.com.*', resourceTypes: ['script', 'image', 'sub_frame'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*adform\\.net.*', resourceTypes: ['script', 'image', 'sub_frame'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*adsrvr\\.org.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*advertising\\.com.*', resourceTypes: ['script', 'image', 'sub_frame'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*hotjar\\.com.*', resourceTypes: ['script', 'websocket'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*mixpanel\\.com.*', resourceTypes: ['script', 'beacon', 'xmlhttprequest'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*segment\\.io.*', resourceTypes: ['script', 'beacon', 'xmlhttprequest'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*amplitude\\.com.*', resourceTypes: ['script', 'beacon', 'xmlhttprequest'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*newrelic\\.com.*', resourceTypes: ['script', 'beacon'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*sentry\\.io.*', resourceTypes: ['script', 'beacon'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*appsflyer\\.com.*', resourceTypes: ['script', 'beacon'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*adjust\\.com.*', resourceTypes: ['script', 'beacon'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*facebook\\.com\\/tr.*', resourceTypes: ['script', 'beacon', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*connect\\.facebook\\.net.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*pixel\\.facebook\\.com.*', resourceTypes: ['script', 'beacon', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*ads\\.yahoo\\.com.*', resourceTypes: ['script', 'image', 'sub_frame'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*ads\\.bing\\.com.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*adservice\\.google\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*ads\\.tiktok\\.com.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*analytics\\.tiktok\\.com.*', resourceTypes: ['script', 'beacon'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*ads\\.linkedin\\.com.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*ads\\.twitter\\.com.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*ads\\.instagram\\.com.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*ads\\.reddit\\.com.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*ads\\.pinterest\\.com.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*\\/ads\\/.*', resourceTypes: ['script', 'image', 'sub_frame', 'xmlhttprequest'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*pagead.*', resourceTypes: ['script', 'image', 'sub_frame'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*\\/advertisement.*', resourceTypes: ['script', 'image', 'sub_frame'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*tracking.*', resourceTypes: ['script', 'beacon', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*pixel.*', resourceTypes: ['image', 'beacon'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*beacon.*', resourceTypes: ['beacon', 'script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*analytics.*', resourceTypes: ['script', 'beacon'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*counter.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*\\/banners\\/.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*\\.adtech.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*adroll\\.com.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*perfectaudience\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*comscore\\.com.*', resourceTypes: ['script', 'beacon'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*omniture\\.com.*', resourceTypes: ['script', 'beacon'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*2mdn\\.net.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*2o7\\.net.*', resourceTypes: ['script', 'beacon'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*bluekai\\.com.*', resourceTypes: ['script', 'beacon'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*krxd\\.net.*', resourceTypes: ['script', 'beacon'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*demdex\\.net.*', resourceTypes: ['script', 'beacon'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*omtrdc\\.net.*', resourceTypes: ['script', 'beacon'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*quantserve\\.com.*', resourceTypes: ['script', 'beacon'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*scorecardresearch\\.com.*', resourceTypes: ['script', 'beacon'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*popads\\.net.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*popcash\\.net.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*propellerads\\.com.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*adcash\\.com.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*zergnet\\.com.*', resourceTypes: ['script', 'image', 'sub_frame'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*teads\\.tv.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*infolinks\\.com.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*moatads\\.com.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*serving-sys\\.com.*', resourceTypes: ['script', 'image', 'sub_frame'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*3lift\\.com.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*admixer\\.net.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*contextweb\\.com.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*lijit\\.com.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*yieldmo\\.com.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*sonobi\\.com.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*triplelift\\.com.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*sharethrough\\.com.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*sovrn\\.com.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*gumgum\\.com.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*undertone\\.com.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*rhythmone\\.com.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*districtm\\.io.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*spotxchange\\.com.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*indexww\\.com.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*mathtag\\.com.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*33across\\.com.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*adcolony\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*admob\\.com.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*unity3d\\.com.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*vungle\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*chartboost\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*ironsource\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*applovin\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*mopub\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*smaato\\.net.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*smartclip\\.net.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*simpli\\.fi.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*eyeota\\.net.*', resourceTypes: ['script', 'beacon'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*tapad\\.com.*', resourceTypes: ['script', 'beacon'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*rlcdn\\.com.*', resourceTypes: ['script', 'beacon'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*bounceexchange\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*addthis\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*sharethis\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*addtoany\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*sumo\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*optimizely\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*branch\\.io.*', resourceTypes: ['script', 'beacon'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*bugsnag\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*logrocket\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*fullstory\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*mouseflow\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*crazyegg\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*heap\\.io.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*heapanalytics\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*kissmetrics\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*intercom\\.io.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*drift\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*zendesk\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*freshdesk\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*livechat\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*olark\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*tawk\\.to.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*liveperson\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*intercomcdn\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*nr-data\\.net.*', resourceTypes: ['beacon'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*segmentify\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*permutive\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*nativo\\.com.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*distroscale\\.com.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*vidazoo\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*wistia\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*mux\\.com.*', resourceTypes: ['beacon'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*kochava\\.com.*', resourceTypes: ['script', 'beacon'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*singular\\.net.*', resourceTypes: ['script', 'beacon'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*tenjin\\.io.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*mparticle\\.com.*', resourceTypes: ['script', 'beacon'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*urbanairship\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*airship\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*leanplum\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*onesignal\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*pushwoosh\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*pushengage\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*webpushr\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*pushcrew\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*convert\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*vwo\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*wingify\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*dynamicyield\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*monetate\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*qubit\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*evergage\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*onetrust\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*consensu\\.org.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*trustarc\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*cookiebot\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*quantcast\\.mgr\\.consensu.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*sp-prod\\.net.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*outreach\\.io.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*driftinsight\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*marketo\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*pardot\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*eloqua\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*hs-analytics\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*hs-scripts\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*hsforms\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*youtube\\.com\\/api\\/ads.*', resourceTypes: ['json', 'xmlhttprequest'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*youtube\\.com\\/ptracks.*', resourceTypes: ['xmlhttprequest'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*youtube\\.com\\/youtubei\\/v1\\/ad.*', resourceTypes: ['json', 'xmlhttprequest'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*s\\.ytimg\\.com.*ad.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*i\\.ytimg\\.com.*ad.*', resourceTypes: ['image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*doubleverify\\.com.*', resourceTypes: ['script', 'beacon'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*integralads\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*adsymptotic\\.com.*', resourceTypes: ['script', 'beacon'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*turn\\.com.*', resourceTypes: ['script', 'beacon'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*matomy\\.com.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*liveramp\\.com.*', resourceTypes: ['script', 'beacon'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*exelator\\.com.*', resourceTypes: ['script', 'beacon'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*imrworldwide\\.com.*', resourceTypes: ['script', 'beacon'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*exponential\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*adition\\.com.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*xandr\\.com.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*mediavine\\.com.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*mediamath\\.com.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*netmng\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*nexac\\.com.*', resourceTypes: ['script', 'beacon'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*innovid\\.com.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*ibride\\.io.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*tvsquared\\.com.*', resourceTypes: ['script', 'beacon'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*bat\\.bing\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*analytics\\.bing\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*px\\.ads\\.linkedin\\.com.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*snap\\.licdn\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*shreddit\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*t\\.co.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*ads-twitter\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*pinimg\\.com.*ct.*', resourceTypes: ['image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*tr\\.pinterest\\.com.*', resourceTypes: ['script', 'beacon'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*graph\\.instagram\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*pixel\\.instagram\\.com.*', resourceTypes: ['script', 'beacon'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*an\\.fb\\.com.*', resourceTypes: ['script', 'beacon'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*fbcdn\\.net\\/ads\\/.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*aax\\.amazon-adsystem\\.com.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*flashtalkingdotcom\\.doubleverify\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*pulsepoint\\.com.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*revcontent\\.com.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*content\\.ad.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*audience2\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*intellitix\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*merkle-rmg\\.com.*', resourceTypes: ['script', 'beacon'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*cdn\\.cookielaw\\.org.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*evidon\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*mktomr\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*f\\.bl\\.is.*', resourceTypes: ['script', 'beacon'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*advertising\\.amazon\\.com.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*smaato\\.net.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*yahoo\\.com\\/ads.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*yahoo\\.com\\/beacon.*', resourceTypes: ['beacon'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*bing\\.com\\/\\/bat.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*adnexus\\.net.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*advertising\\.yahoo\\.com.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*chase\\.com\\/ads.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*bankofamerica\\.com\\/ads.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*wellsfargo\\.com\\/ads.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*cit\\.com\\/ads.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*usbank\\.com\\/ads.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*capitalone\\.com\\/ads.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*discover\\.com\\/ads.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*americanexpress\\.com\\/ads.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*bbva\\.com\\/ads.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*hsbc\\.com\\/ads.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*barclays\\.com\\/ads.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.* Santander.*ads.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*ing\\.com\\/ads.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*dbs\\.com\\/ads.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*ubs\\.com\\/ads.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*goldmansachs\\.com\\/ads.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*ms\\.com\\/ads.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*和要求.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*广告.*', resourceTypes: ['script', 'image', 'sub_frame'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*\\.cn\\/ads.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*baidu\\.com.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*sina\\.com\\.cn\\/ads.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*sohu\\.com\\/ads.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*ifeng\\.com\\/ads.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*youku\\.com\\/ads.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*iqiyi\\.com\\/ads.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*douban\\.com\\/ads.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*taobao\\.com\\/ads.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*alibaba\\.com\\/ads.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*jd\\.com\\/ads.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*pinduoduo\\.com\\/ads.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*bilibili\\.com\\/ads.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*xiongzhang\\.ads.*', resourceTypes: ['script'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*tiktokv\\.com\\/api\\/ad.*', resourceTypes: ['json'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*muscdn\\.com\\/ad.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*kuaishou\\.com\\/ad.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*kuaishouvideo\\.com\\/ad.*', resourceTypes: ['script', 'image'] } },
  { id: idCounter++, priority: 1, action: { type: 'block' }, condition: { urlFilter: '.*bilibili\\.com\\/x\\/web\\/view\\/ad.*', resourceTypes: ['json'] } }
];

function updateRules(add) {
  if (add && isEnabled) {
    chrome.declarativeNetRequest.updateDynamicRules({
      addRules: adRules
    });
  } else {
    const ruleIds = adRules.map(r => r.id);
    chrome.declarativeNetRequest.updateDynamicRules({
      removeRuleIds: ruleIds
    });
  }
}

chrome.runtime.onInstalled.addListener(() => {
  updateRules(true);
  chrome.storage.local.set({ enabled: true, blockedCount: 0, trackingCount: 0, darkTheme: true });
});

if (chrome.declarativeNetRequest?.onRuleMatchedDebug) {
  chrome.declarativeNetRequest.onRuleMatchedDebug.addListener((info) => {
    chrome.storage.local.get('blockedCount', (result) => {
      const newCount = (result.blockedCount || 0) + 1;
      chrome.storage.local.set({ blockedCount: newCount });
    });
  });
}

chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
  if (message.type === 'TOGGLE_EXTENSION') {
    isEnabled = message.enabled;
    updateRules(message.enabled);
  }
  if (message.type === 'REFRESH_RULES') {
    updateRules(false);
    setTimeout(() => updateRules(true), 100);
  }
  if (message.type === 'AD_BLOCKED') {
    chrome.storage.local.get('blockedCount', (result) => {
      const newCount = (result.blockedCount || 0) + 1;
      chrome.storage.local.set({ blockedCount: newCount });
    });
  }
  if (message.type === 'TRACKER_BLOCKED') {
    chrome.storage.local.get('trackingCount', (result) => {
      const newCount = (result.trackingCount || 0) + 1;
      chrome.storage.local.set({ trackingCount: newCount });
    });
  }
});
